# Generated by Django 2.0.4 on 2018-04-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_coach', models.CharField(max_length=200)),
                ('years', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('rut_coach', models.CharField(max_length=100)),
                ('nickname_coach', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_game', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_player', models.CharField(max_length=200)),
                ('nickname_player', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('years', models.IntegerField()),
                ('rut_player', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo_team', models.ImageField(upload_to='')),
                ('code_team', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='code_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basquet.Team'),
        ),
        migrations.AddField(
            model_name='coach',
            name='code_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basquet.Team'),
        ),
    ]
